# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f79e8665767d0820fc87b03129537a1b01c5bd6e2569f8d16419399da07658bdb6b017c53bb11ca6775789f61f041ed125409be990c78d3c7f7e2026c47dbb03

test:
  secret_key_base: 98820e0d4544344e5fb41f52cb334ec50b1e9436ccb72c5fc401d1935085a3c29a3033d031ea5d59c5921bfb96d440574281b632552c6c1b815dd74a8d01b142

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
